name: spnet

services:
  web:
    image: securepipeline360:local
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - spnet

networks:
  spnet:
    name: spnet
