name: SecurePipeline360 CI (Build + Security Scans)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write   # allow uploading SARIF to code scanning

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t securepipeline360:ci .

      # ---------- Trivy: scan the built image ----------
      - name: Trivy (image) — detect critical/high CVEs and fail
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: securepipeline360:ci
          format: sarif
          output: trivy-image.sarif
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '1'   # fail pipeline if CRITICAL/HIGH found

      - name: Upload Trivy SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif

      # ---------- Trivy: scan the repo filesystem ----------
      - name: Trivy (fs) — scan dependencies in repo
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          format: sarif
          output: trivy-fs.sarif
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '1'

      - name: Upload Trivy FS SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif

      # ---------- Checkov: IaC misconfigurations ----------
      - name: Checkov — scan IaC (Terraform / K8s / Docker)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          output_format: sarif
          output_file_path: checkov.sarif
          soft_fail: false     # fail on failed checks (recommended)
          framework: terraform,kubernetes,github_actions,dockerfile

      - name: Upload Checkov SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif

      # ---------- Keep HTML reports as artifacts (optional) ----------
      - name: Archive SARIF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            trivy-image.sarif
            trivy-fs.sarif
            checkov.sarif