name: SecurePipeline360 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  security-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t securepipeline360:local .

      # ---------- Trivy FS ----------
      - id: trivy_fs
        name: Trivy FS scan (repo)
        uses: aquasecurity/trivy-action@0.24.0
        continue-on-error: true
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-fs.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          exit-code: '1'   # mark failure, but don't stop job

      - name: Upload Trivy FS SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif

      - name: Upload Trivy FS artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs.sarif
          path: trivy-fs.sarif

      # ---------- Trivy Image ----------
      - id: trivy_image
        name: Trivy Image scan
        uses: aquasecurity/trivy-action@0.24.0
        continue-on-error: true
        with:
          scan-type: 'image'
          image-ref: 'securepipeline360:local'
          format: 'sarif'
          output: 'trivy-image.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: Upload Trivy Image SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif

      - name: Upload Trivy Image artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image.sarif
          path: trivy-image.sarif

      # ---------- Checkov IaC ----------
      - id: checkov
        name: Checkov IaC scan
        uses: bridgecrewio/checkov-action@v12   # pin a release, not master
        continue-on-error: true
        with:
          directory: .
          output_format: sarif
          output_file_path: checkov.sarif
          quiet: true

      - name: Upload Checkov SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif

      - name: Upload Checkov artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov.sarif
          path: checkov.sarif

      # ---------- Final Gate ----------
      - name: Gate on High/Critical
        if: always()
        run: |
          fail=0
          echo "Trivy FS outcome:      ${{ steps.trivy_fs.outcome }}"
          echo "Trivy Image outcome:   ${{ steps.trivy_image.outcome }}"
          echo "Checkov outcome:       ${{ steps.checkov.outcome }}"
          for o in "${{ steps.trivy_fs.outcome }}" "${{ steps.trivy_image.outcome }}" "${{ steps.checkov.outcome }}"; do
            if [ "$o" = "failure" ]; then fail=1; fi
          done
          if [ $fail -ne 0 ]; then
            echo "One or more scanners reported HIGH/CRITICAL findings. Failing the job."
            exit 1
          fi
