name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t securepipeline360 .

      - name: Run Trivy scan (image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: securepipeline360
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .

      - name: Run OWASP ZAP baseline scan
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py           -t http://example.com -r zap_report.html
